python ./lerobot_lsy/src/lerobot/scripts/train.py \
    --job_name=dit_flow_mt_franka_pretrain \
    --output_dir=./outputs/real/dit_flow_mt_franka_pretrain \
    --dataset.repo_id=continuallearning/pretraining_v2_lerobot30 \
    --policy.type=dit_flow_mt \
    --policy.push_to_hub=false \
    --batch_size=32 \
    --num_workers=16 \
    --steps=200000 \
    --eval_freq=0 \
    --save_freq=50000 \
    --log_freq=500 \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer;
