export MUJOCO_GL=egl;
export CUDA_VISIBLE_DEVICES=0;
export MUJOCO_EGL_DEVICE_ID=0;
SEED=${1:-42};

DATASET_ROOT=continuallearning;
CHECKPOINT_ROOT=./outputs;

STEPS=20000;
LOG_STEPS=100;
N_EVAL=100;
BS_EVAL=25;

PRETRAIN_PATH=/home/ralf_roemer/projects/clare/outputs/dit_flow_mt_libero_90_pretrain_new;

# Task 0: no replay buffer yet, identical to SeqFFT
# python ./lerobot_lsy/src/lerobot/scripts/train_eval_multi.py \
#     --seed=$SEED \
#     --job_name=er_seed_${SEED}_libero_goal_task_0 \
#     --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_0 \
#     --dataset.repo_id=continuallearning/libero_goal_image_task_0 \
#     --policy.path=$PRETRAIN_PATH \
#     --policy.push_to_hub=false \
#     --batch_size=16 \
#     --num_workers=8 \
#     --steps=$STEPS \
#     --env.type=libero \
#     --env.benchmark=libero_goal \
#     --env.task=Libero_Goal_Task_0 \
#     --eval.batch_size=$BS_EVAL \
#     --eval.n_episodes=$N_EVAL \
#     --eval.max_episodes_rendered=4 \
#     --eval_freq=$STEPS \
#     --save_freq=$STEPS \
#     --log_freq=$LOG_STEPS \
#     --wandb.enable=true \
#     --wandb.disable_artifact=true \
#     --wandb.project=clare_experiments \
#     --wandb.entity=ralf-roemer \
# && \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_1 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_1 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_1 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_er \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_0/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_2 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_2 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_2 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_1 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_1/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_3 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_3 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_3 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_2 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_2/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_4 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_4 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_4 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_3 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_3/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_5 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_5 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_5 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_4 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_4/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4,Libero_Goal_Task_5 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_6 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_6 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_6 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_5 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_5/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4,Libero_Goal_Task_5,Libero_Goal_Task_6 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_7 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_7 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_7 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_6 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_6/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4,Libero_Goal_Task_5,Libero_Goal_Task_6,Libero_Goal_Task_7 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_8 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_8 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_8 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_7 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_7/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4,Libero_Goal_Task_5,Libero_Goal_Task_6,Libero_Goal_Task_7,Libero_Goal_Task_8 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer \
&& \
python ./lerobot_lsy/src/lerobot/scripts/er.py \
    --seed=$SEED \
    --job_name=er_seed_${SEED}_libero_goal_task_9 \
    --output_dir=./outputs/er/er_seed_${SEED}_libero_goal_task_9 \
    --dataset.repo_id=continuallearning/libero_goal_image_task_9 \
    --replay_dataset.repo_id=continuallearning/libero_goal_image_task_0_8 \
    --policy.path=./outputs/er/er_seed_${SEED}_libero_goal_task_8/checkpoints/last/pretrained_model \
    --policy.push_to_hub=false \
    --batch_size=16 \
    --num_workers=8 \
    --replay_batch_size=16 \
    --replay_num_workers=8 \
    --steps=$STEPS \
    --env.type=libero \
    --env.benchmark=libero_goal \
    --env.task=Libero_Goal_Task_0,Libero_Goal_Task_1,Libero_Goal_Task_2,Libero_Goal_Task_3,Libero_Goal_Task_4,Libero_Goal_Task_5,Libero_Goal_Task_6,Libero_Goal_Task_7,Libero_Goal_Task_8,Libero_Goal_Task_9 \
    --eval.batch_size=$BS_EVAL \
    --eval.n_episodes=$N_EVAL \
    --eval.max_episodes_rendered=4 \
    --eval_freq=$STEPS \
    --save_freq=$STEPS \
    --log_freq=$LOG_STEPS \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=clare_experiments \
    --wandb.entity=ralf-roemer;
